# Generated by Django 4.2.3 on 2023-07-06 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_color_blue_alter_color_green_alter_color_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='blue',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='color',
            name='green',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='color',
            name='red',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(255)]),
        ),
    ]
